services:
  postgres:
    image: postgres:18

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql

  postgres-test:
    profiles:
      - test
    image: postgres:18

    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - pgtestdata:/var/lib/postgresql

  backend:
    image: ledger-backend
    
    build: 
      context: .
      dockerfile: backend/Dockerfile

    ports: 
      - "5001:5001"

    environment:
      APP_ENV: development
      NODE_ENV: production
      PORT: 5001
      FRONTEND_URL: http://localhost:3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
    pgdata:
    pgtestdata: